### ISSUE TITLE
Bug: decimal values are not save correctly

### ISSUE THREAD

**Issue by majdisorder** [dimi3tron/data.dump#5]
The decimal part seems to get dropped

**Comment by dimi3tron** [comment]
Fixed by forcing precision to (18, 9) on table creation. This seemed like a sensible value. May need to make it variable in the future. 

Closing for now.

**Comment by majdisorder** [comment]
Fixed by forcing precision to (18, 9) on table creation. This seemed like a sensible value. May need to make it variable in the future.

Closing for now.
